db:
  environment:
    MYSQL_ROOT_PASSWORD: example
  image: mariadb
  volumes:
  - ${vol_name}:/var/lib/mysql
  volume_driver: nutanix
www:
  ports:
  - ${public_port}:80/tcp
  environment:
    WORDPRESS_DB_PASSWORD: example
  image: wordpress
  links:
  - db:mysql
